const actions = {
	//MilkMan
	LOAD_MILKMANS: 'LOAD_MILKMANS',
	LOAD_MILKMANS_ERROR: 'LOAD_MILKMANS_ERROR',

	//Milk
	LOAD_MILK_REPORTS: 'LOAD_MILK_REPORTS',
	LOAD_MILK_REPORTS_ERROR: 'LOAD_MILK_REPORTS_ERROR',

	//Milk Producer
	LOAD_MILK_PRODUCERS: 'LOAD_MILK_PRODUCERS',
	LOAD_MILK_PRODUCERS_ERROR: 'LOAD_MILK_PRODUCERS_ERROR',

	//Milk Request
	LOAD_MILK_REQUESTS: 'LOAD_MILK_REQUESTS',
	LOAD_MILK_REQUESTS_ERROR: 'LOAD_MILK_REQUESTS_ERROR',
};

export default actions;
